on: push
name: GitHub Pages
jobs:
  filterMasterBranch:
    name: Filter master branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter master branch
      uses: actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da
      with:
        args: branch master
    - name: Install Dependencies
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
